import sys
import re

file_path = 'c:/Users/urvas/OneDrive/Desktop/CodeCrafters/CodeCrafter_Mango/sage-fin-compass-main/src/pages/Search.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Add toast to imports and 'X' icon for overlay
if 'from "sonner"' not in content:
    content = content.replace('import { useWatchlist }', 'import { toast } from "sonner";\nimport { useWatchlist }')

if 'X,' not in content and 'X } from' not in content:
    content = content.replace('from "lucide-react";', 'X } from "lucide-react";')

# 2. Add state for selectedNews
state_anchor = 'const [expandedId, setExpandedId] = useState<string | null>(null);'
new_state = state_anchor + '''
  const [selectedNews, setSelectedNews] = useState<NewsItem | null>(null);

  const handleDownloadReport = (type: string, quarter: string, symbol: string) => {
    const html = `<html><head><title>${symbol} ${quarter} ${type}</title><style>body{font-family:'Segoe UI',system-ui,sans-serif;max-width:800px;margin:40px auto;line-height:1.6;color:#333}h1{color:#16a34a;border-bottom:2px solid #16a34a;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin:20px 0}th,td{border:1px solid #ddd;padding:12px;text-align:left}th{background:#f8faff;color:#16a34a}.footer{margin-top:50px;font-size:12px;color:#888;text-align:center}</style></head><body><h1>${symbol} Corporation</h1><h2>${quarter} ${type}</h2><p>This document serves as the official financial disclosure for ${symbol} for the period of ${quarter}.</p><h3>Financial Highlights</h3><table><tr><th>Metric</th><th>Value (in Cr)</th><th>YoY Growth</th></tr><tr><td>Revenue</td><td>₹12,450</td><td style="color:green">+14.2%</td></tr><tr><td>EBITDA</td><td>₹3,120</td><td style="color:green">+18.5%</td></tr><tr><td>Net Profit</td><td>₹1,890</td><td style="color:green">+12.1%</td></tr></table><h3>Management Discussion</h3><p>The company has demonstrated resilient growth across all core segments despite macroeconomic headwinds. Strong execution in the digital transformation pipeline yielded unprecedented margins in the current quarter.</p><div class="footer">CONFIDENTIAL - Generated by Sage FinCompass AI System</div></body></html>`;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${symbol}_${quarter}_${type.replace(/ /g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Successfully downloaded ${quarter} ${type}`);
  };

  const handleAddToWatchlist = (symbol: string) => {
    addToWatchlist(symbol);
    toast.success(`${symbol} has been securely tracked in your Watchlist!`);
  };
'''
content = content.replace(state_anchor, new_state)

# 3. Modify handleSearch and SelectedSector
# Original:
# onChange={(e) => setSelectedSector(e.target.value)}
# We want to use useEffect for selectedSector
effect_inject = '''
  import { useEffect } from "react";
'''
if 'useEffect' not in content:
    content = content.replace('import { useState, useMemo }', 'import { useState, useMemo, useEffect }')

# Fix handleSearch to use current state params properly or just add useEffect
useeffect_state = '''
  useEffect(() => {
    if (query.trim() !== "" || selectedSector !== "All Sectors") {
      const q = query.toLowerCase();
      const filtered = newsData.filter(
        (n) =>
          n.title.toLowerCase().includes(q) ||
          n.summary.toLowerCase().includes(q) ||
          n.relatedCompanies.some((c) => c.toLowerCase().includes(q)) ||
          n.tags.some((t) => t.toLowerCase().includes(q))
      );
      setResults(filtered.length > 0 ? filtered : newsData);
      setSearched(true);
    }
  }, [selectedSector]);
'''
content = content.replace('const categories =', useeffect_state + '\n  const categories =')

# 4. Replace buttons inside Search
# addToWatchlist
content = content.replace('onClick={() => addToWatchlist(', 'onClick={() => handleAddToWatchlist(')

# Download button
download_btn = '<Button variant="ghost" size="icon" className="group-hover:text-primary group-hover:bg-primary/10 transition-colors">'
download_btn_new = '<Button onClick={() => handleDownloadReport(report.type, report.quarter, mainStock.symbol)} variant="ghost" size="icon" className="group-hover:text-primary group-hover:bg-primary/10 transition-colors">'
content = content.replace(download_btn, download_btn_new)

# News onclick to overlay
# Find the mapping of `filteredResults.slice(0, 3).map((item) => (`
# Replace `<div key={item.id} className="glass-card` with `<div key={item.id} onClick={() => setSelectedNews(item)} className="cursor-pointer glass-card`
news_card = '<div key={item.id} className="glass-card p-5 transition-all hover:border-primary/30">'
news_card_new = '<div key={item.id} onClick={() => setSelectedNews(item)} className="cursor-pointer glass-card p-5 shadow-sm transition-all hover:shadow-md hover:border-primary/50">'
content = content.replace(news_card, news_card_new)

# Similarly for the results that appear if not searching a main stock:
# They are below {/* Results */}
content = content.replace(
    '<div key={item.id} className="glass-card p-5 transition-all hover:border-primary/30">',
    '<div key={item.id} onClick={() => setSelectedNews(item)} className="cursor-pointer glass-card p-5 shadow-sm transition-all hover:shadow-md hover:border-primary/50">'
)

# 5. Add Overlay JSX before <Footer />
overlay_jsx = '''
      {selectedNews && (
        <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm animate-in fade-in flex items-center justify-center p-4 sm:p-6 overflow-y-auto">
          <div className="glass-card w-full max-w-4xl max-h-[90vh] overflow-y-auto shadow-2xl relative animate-in zoom-in-95 duration-200 border-primary/20">
            <Button
              variant="ghost"
              size="icon"
              className="absolute right-4 top-4 rounded-full bg-background/50 hover:bg-destructive hover:text-destructive-foreground z-10"
              onClick={() => setSelectedNews(null)}
            >
              <X className="h-5 w-5" />
            </Button>
            
            <div className="p-8 sm:p-12">
              <div className="flex items-center gap-3 mb-6 flex-wrap">
                <Badge className="bg-primary/10 text-primary hover:bg-primary/20 border-none">{selectedNews.category}</Badge>
                <div className="flex items-center gap-2 text-sm text-muted-foreground font-medium">
                  <Clock className="h-4 w-4" />
                  {selectedNews.date}
                </div>
                <div className="flex items-center gap-2 ml-auto">
                  <span className={`inline-block h-2.5 w-2.5 rounded-full ${
                    selectedNews.sentiment === "positive" ? "bg-primary" : selectedNews.sentiment === "negative" ? "bg-destructive" : "bg-warning"
                  } shadow-sm`} />
                  <span className="text-sm font-semibold capitalize text-muted-foreground">
                    {selectedNews.sentiment} Sentiment
                  </span>
                </div>
              </div>

              <h2 className="font-heading text-3xl sm:text-4xl font-bold leading-tight mb-8">
                {selectedNews.title}
              </h2>

              <div className="bg-primary/5 border border-primary/20 rounded-xl p-6 mb-10 shadow-sm relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1.5 h-full bg-primary" />
                <h3 className="text-sm font-bold text-primary flex items-center gap-2 mb-3 tracking-wide uppercase">
                  <Sparkles className="h-4 w-4" /> AI Generated Summary
                </h3>
                <p className="text-foreground/90 leading-relaxed font-medium">
                  {selectedNews.summary}
                </p>
              </div>

              <div className="prose prose-slate dark:prose-invert max-w-none">
                <p className="text-lg leading-relaxed text-slate-700 dark:text-slate-300 font-serif whitespace-pre-line">
                  {selectedNews.fullContent || "Extensive market analysis and comprehensive breakdown of the core strategic components associated with this development."}
                </p>
              </div>
              
              <div className="mt-12 pt-8 border-t border-border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
                <div className="space-y-2">
                  <p className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">Related Assets</p>
                  <div className="flex flex-wrap gap-2">
                    {selectedNews.relatedCompanies.map(c => (
                      <Badge key={c} variant="outline" className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-colors" onClick={() => { setSelectedNews(null); setQuery(c); handleSearch(); }}>
                        {c}
                      </Badge>
                    ))}
                  </div>
                </div>
                <Button variant="outline" className="gap-2 shrink-0 shadow-sm font-semibold" onClick={() => window.open(selectedNews.sourceUrl, '_blank')}>
                  Read source on {selectedNews.source} <ExternalLink className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
'''

content = content.replace('<Footer />', overlay_jsx + '\n      <Footer />')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Patch applied")
